### ISSUE TITLE
希望提供更多的文档和架构图

### ISSUE THREAD

**Issue by standup-jb** [ppdaicorp/pmq#2]
有系统架构图和组件直接的关系图吗？以及简单介绍一下如何做到保证你们提出的那些功能。
支持动态重平衡
支持动态修改偏移量
支持动态修改线程数
支持动态修改延迟时间
支持动态设置黑白名单
支持动态修改批量消费条数
支持消息发送令牌防止乱发
支持动态启停消费
支持自助创建topic，自助扩容
支持自助创建消费者组
支持自助添加和解除绑定topic
支持一个应用订阅多个消费者组
失败消息重新消费
支持消息无缝迁移

**Comment by lorgine** [comment]
里面有个doc 文档 里面有个介绍。
这里也有个文章来介绍。更多的说明后续会慢慢提供
https://mp.weixin.qq.com/s/5e-yC0r18FZ04vMvGxIL-w
