### ISSUE TITLE
待处理消息数为负

### ISSUE THREAD

**Issue by jianhualuoying** [ppdaicorp/pmq#23]
UI界面“队列消费管理”中，消费者组的待处理消息数为负，按照UI界面的提示：
>2.待处理消息数为负时，待处理消息数显示为红色。影响消费，需要及时处理！
    问题原因：当偏移值大于数据表的最大Id时，会出现待处理消息数为负的问题。
    解决办法：手动修改偏移，让偏移值小于当前数据表的最大Id。

发现需要设置偏移值大于数据表的最大Id，但是发现消费表的最大Id为0，也就是无法消费。请问哪里能设置消息表的最大ID？
截图如下：
![Snipaste_2021-05-23_11-58-57](https://user-images.githubusercontent.com/12456632/119247832-77eb7780-bbbf-11eb-94b4-066aaf5de5af.png)
![Snipaste_2021-05-23_12-00-01](https://user-images.githubusercontent.com/12456632/119247833-791ca480-bbbf-11eb-8537-c95ded9cdbb2.png)

**Comment by csx-java** [comment]
遇到同样的问题

**Comment by lorgine** [comment]
遇到消息为负数的，点击智能修复一下，这个只是影响待处理消息的展示，原因在于字典表的最大id 在消息长时间不用的情况，会出现auto_increment 同步问题。
