### ISSUE TITLE
偏移量一直自动增加

### ISSUE THREAD

**Issue by csx-java** [ppdaicorp/pmq#25]
根据5.1.1修复待处理消息
https://github.com/ppdaicorp/pmq/commit/dde8ec9b4cd524e22a190505197857d1d284e75b

![image](https://user-images.githubusercontent.com/31872268/119291406-f8be7800-bc80-11eb-8348-8385045548ac.png)
偏移量一直递增
![image](https://user-images.githubusercontent.com/31872268/119291067-66b66f80-bc80-11eb-848d-072e1ebd05a8.png)

**Comment by lorgine** [comment]
是的

**Comment by csx-java** [comment]
我想知道为什么




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ppdaicorp/pmq"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月24日(星期一) 中午11:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ppdaicorp/pmq] 偏移量一直自动增加 (#25)





 
是的

**Comment by lorgine** [comment]
> 我想知道为什么
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ppdaicorp/pmq" ***@***.***&gt;; 发送时间:&nbsp;2021年5月24日(星期一) 中午11:15 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [ppdaicorp/pmq] 偏移量一直自动增加 (#25) 是的 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

消息消费完了，偏移量就会增加。偏移量相当于一个消费指针。

**Comment by csx-java** [comment]
待处理消息一条也没有，我测试接口触发了几次，总消息也没有




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ppdaicorp/pmq"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月24日(星期一) 中午11:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ppdaicorp/pmq] 偏移量一直自动增加 (#25)





 
是的

**Comment by lorgine** [comment]
加群私聊

> 待处理消息一条也没有，我测试接口触发了几次，总消息也没有
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ppdaicorp/pmq" ***@***.***&gt;; 发送时间:&nbsp;2021年5月24日(星期一) 中午11:15 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [ppdaicorp/pmq] 偏移量一直自动增加 (#25) 是的 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by csx-java** [comment]
加了好多次，没有人同意




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ppdaicorp/pmq"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月24日(星期一) 中午11:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ppdaicorp/pmq] 偏移量一直自动增加 (#25)





 
加群私聊
  
待处理消息一条也没有，我测试接口触发了几次，总消息也没有
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ppdaicorp/pmq" @.&gt;; 发送时间:&nbsp;2021年5月24日(星期一) 中午11:15 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [ppdaicorp/pmq] 偏移量一直自动增加 (#25) 是的 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by lorgine** [comment]
再加
