### ISSUE TITLE
源码down到本地，有如下几个类not found

### ISSUE THREAD

**Issue by zdhuangelephant** [ppdaicorp/pmq#4]
import com.ppdai.infrastructure.mq.biz.common.trace.CatContext;
import com.ppdai.infrastructure.mq.biz.common.trace.Tracer;
import com.ppdai.infrastructure.mq.biz.common.trace.spi.Transaction;
import com.ppdai.infrastructure.mq.biz.dto.BaseResponse;
com.ppdai.infrastructure.mq.biz.dto包下很多类都找不到呢，是需要动态生成吗？

**Comment by lorgine** [comment]
需要先在client目录下，先install一下。有问题，可以加入支持群。
