### ISSUE TITLE
为什么订阅关系除了在配置文件中写，还要手动再添加一遍，有什么好处吗？

### ISSUE THREAD

**Issue by ruqinhu** [ppdaicorp/pmq#5]

**Comment by lorgine** [comment]
订阅关系除了关系之外，还有很多治理功能，如重试次数，超时时间，线程数等。同时在创建订阅关系的时候，会初始化很多其他的操作。本地配置文件，更强调的是这个订阅的处理方法。

**Comment by lorgine** [comment]
还有一个在界面会指定消息量，来预估队列数。这些信息本地xml是没有的。还有一个就是如果根据本地xml 动态生成的话 会产生很多的垃圾数据。
