### ISSUE TITLE
有性能测试报告么？

### ISSUE THREAD

**Issue by JoeCqupt** [ppdaicorp/pmq#6]
这个比kafka的性能差多少？使用mysql做序列化感觉性能不会比kafka性能好吧

**Comment by lorgine** [comment]
第一我们是用在高可靠的业务系统，基本可以保证消息不丢失。第二我们存储的是字符串，而且broker和存储分离，序列化没有瓶颈。第三你可以看到这个介绍，监控治理功能很强大。第四我们在生产上高峰1.3万发送qps。
